//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 0.5.5559.28274.
namespace Schemas.Sushi
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ReportResponse", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ReportResponse", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schemas.Sushi.Counter.CounterReportResponse))]
    public partial class ReportResponse
    {
        
        /// <summary>
        /// <para>One or more exceptions found in the request or while processing the request.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Exception", Namespace="http://www.niso.org/schemas/sushi", IsNullable=true)]
        public System.Collections.ObjectModel.Collection<Exception> Exception { get; private set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Exception collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionSpecified
        {
            get
            {
                return (this.Exception.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReportResponse" /> class.</para>
        /// </summary>
        public ReportResponse()
        {
            this.Exception = new System.Collections.ObjectModel.Collection<Exception>();
        }
        
        /// <summary>
        /// <para>Repeated from the ReportRequest. The service or instance of the service requesting the report. </para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Requestor", Namespace="http://www.niso.org/schemas/sushi")]
        public Requestor Requestor { get; set; }
        
        /// <summary>
        /// <para>Repeated from the ReportRequest. The customer whose usage is being reported.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CustomerReference", Namespace="http://www.niso.org/schemas/sushi")]
        public CustomerReference CustomerReference { get; set; }
        
        /// <summary>
        /// <para>Repeated from the ReportRequest. Defines the report being requested.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReportDefinition", Namespace="http://www.niso.org/schemas/sushi")]
        public ReportDefinition ReportDefinition { get; set; }
        
        /// <summary>
        /// <para>Date/time the response was created.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Created", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Created { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Created property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified { get; set; }
        
        /// <summary>
        /// <para>If the ReportRequest had an ID, return in this attribute.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string ID { get; set; }
    }
    
    /// <summary>
    /// <para>Service Exceptions</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("Exception", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Exception
    {
        
        /// <summary>
        /// <para>Error Number</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Number", Namespace="http://www.niso.org/schemas/sushi", DataType="int")]
        public int Number { get; set; }
        
        /// <summary>
        /// <para>Severity of the error.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Severity", Namespace="http://www.niso.org/schemas/sushi")]
        public ExceptionSeverity Severity { get; set; }
        
        /// <summary>
        /// <para>Text describing the error.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Message", Namespace="http://www.niso.org/schemas/sushi", DataType="string")]
        public string Message { get; set; }
        
        /// <summary>
        /// <para>URL describing error details.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("HelpUrl", Namespace="http://www.niso.org/schemas/sushi", IsNullable=true, DataType="anyURI")]
        public string HelpUrl { get; set; }
        
        /// <summary>
        /// <para>Other optional data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Data", Namespace="http://www.niso.org/schemas/sushi", IsNullable=true)]
        public object Data { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Created", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Created { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Created property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified { get; set; }
    }
    
    /// <summary>
    /// <para>Service exception levels: Info, Debug, Warning, Error.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ExceptionSeverity", Namespace="http://www.niso.org/schemas/sushi")]
    public enum ExceptionSeverity
    {
        
        /// <summary>
        /// <para>Info – type of severity that provides more information about the response. Can be included in a chain of other severity levels.</para>
        /// </summary>
        Info,
        
        /// <summary>
        /// <para>Debug – type of severity that provides debugging information about the response. Can be included in a chain of other severity levels.</para>
        /// </summary>
        Debug,
        
        /// <summary>
        /// <para>Warning – type of severity that does not interrupt the completion of the transaction (defined as: request-&gt;data-&gt;response) but gives more information about the response. It could be followed by more exceptions (Info, Debug).</para>
        /// </summary>
        Warning,
        
        /// <summary>
        /// <para>Error – type of severity that would return no payload. It could be followed by more exceptions (Info, Debug).</para>
        /// </summary>
        Error,
        
        /// <summary>
        /// <para>Fatal – type of severity that would return no payload. It could be followed by more exceptions (Info, Debug).</para>
        /// </summary>
        Fatal,
    }
    
    /// <summary>
    /// <para>Service consumer(client). Identifies the customer or 3rd party acting on behalf of customer.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("Requestor", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Requestor
    {
        
        /// <summary>
        /// <para>Identifier by which the service (server) knows the service consumer (client). For some services this may be the same as the Customer ID.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="http://www.niso.org/schemas/sushi", DataType="string")]
        public string ID { get; set; }
        
        /// <summary>
        /// <para>Name of the requestor organization. (This is not the name of a person.)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace="http://www.niso.org/schemas/sushi", DataType="string")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Valid e-mail address that service can use to contact a human at the requestor organization.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Email", Namespace="http://www.niso.org/schemas/sushi", DataType="string")]
        public string Email { get; set; }
    }
    
    /// <summary>
    /// <para>A reference to a customer for which data is requested.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("CustomerReference", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerReference
    {
        
        /// <summary>
        /// <para>The Customer ID (usually proprietary) that the service uses to identify the customer. The value of this ID for a given organization will be different for each service.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="http://www.niso.org/schemas/sushi", DataType="string")]
        public string ID { get; set; }
        
        /// <summary>
        /// <para>Customer name</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace="http://www.niso.org/schemas/sushi", IsNullable=true, DataType="string")]
        public string Name { get; set; }
    }
    
    /// <summary>
    /// <para>Input arguments for the report.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ReportDefinition", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportDefinition
    {
        
        /// <summary>
        /// <para>Current filters include mandadory date ranges for the COUNTER usage reports along with optional filters.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Filters", Namespace="http://www.niso.org/schemas/sushi")]
        public ReportDefinitionFilters Filters { get; set; }
        
        /// <summary>
        /// <para>Report name. See http://www.niso.org/workrooms/sushi/reports for a list of registered report names and releases.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>The release number corresponding to the COUNTER Code of Practice when the current definition of the report was introduced.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Release", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string Release { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ReportDefinitionFilters", Namespace="http://www.niso.org/schemas/sushi", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportDefinitionFilters
    {
        
        /// <summary>
        /// <para>The date range for the report. For COUNTER reports statistics are pulled by month; therefore, the date range should cover a range of months.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UsageDateRange", Namespace="http://www.niso.org/schemas/sushi")]
        public Range UsageDateRange { get; set; }
        
        /// <summary>
        /// <para>Optional filters can be added to the request to narrow the request to an IPRange, a department or more.  ONLY use filters known to be supported by the SUSHI server being called.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Filter", Namespace="http://www.niso.org/schemas/sushi")]
        public System.Collections.ObjectModel.Collection<FilterName> Filter { get; private set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Filter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FilterSpecified
        {
            get
            {
                return (this.Filter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReportDefinitionFilters" /> class.</para>
        /// </summary>
        public ReportDefinitionFilters()
        {
            this.Filter = new System.Collections.ObjectModel.Collection<FilterName>();
            this.ReportAttribute = new System.Collections.ObjectModel.Collection<ReportAttribute>();
        }
        
        /// <summary>
        /// <para>Optional report attributes can be added to the request to control the report format.  ONLY use report attributes known to be supported by the SUSHI server being called.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReportAttribute", Namespace="http://www.niso.org/schemas/sushi")]
        public System.Collections.ObjectModel.Collection<ReportAttribute> ReportAttribute { get; private set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReportAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportAttributeSpecified
        {
            get
            {
                return (this.ReportAttribute.Count != 0);
            }
        }
    }
    
    /// <summary>
    /// <para>The Date Range Type made up of Begin and End dates. Note: COUNTER usage is only reported at the month level; therefore, this represents the range of months.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("Range", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Range
    {
        
        /// <summary>
        /// <para>Beginning date of range formatted as "yyyy-mm-dd". Specify 'dd' as  the first day of the month  for COUNTER reports.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Begin", Namespace="http://www.niso.org/schemas/sushi", DataType="date")]
        public System.DateTime Begin { get; set; }
        
        /// <summary>
        /// <para>Ending date of range formatted as "yyyy-mm-dd". Specify 'dd' as  the last day of the month for COUNTER reports.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("End", Namespace="http://www.niso.org/schemas/sushi", DataType="date")]
        public System.DateTime End { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("FilterName", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FilterName
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="string")]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Examples of filter names are: IPRange, Department, Platform.  Support of filters is optional.  Refer to http://www.niso.org/workrooms/sushi for a list of commonly used filters.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string Name { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ReportAttribute", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportAttribute
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="string")]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Examples of report attribute names are: Granularity, ExcludeZeroUsage.  Support of report attributes is optional.  Refer to http://www.niso.org/workrooms/sushi for a list of commonly used filters.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string Name { get; set; }
    }
    
    /// <summary>
    /// <para>Request from SUSHI Client requesting a COUNTER report.</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("ReportRequest", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ReportRequest", Namespace="http://www.niso.org/schemas/sushi/counter")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schemas.Sushi.ReportRequest))]
    public partial class ReportRequest
    {
        
        /// <summary>
        /// <para>Consumer of the service (client).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Requestor", Namespace="http://www.niso.org/schemas/sushi")]
        public Requestor Requestor { get; set; }
        
        /// <summary>
        /// <para>Identity of the customer for which data is requested.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("CustomerReference", Namespace="http://www.niso.org/schemas/sushi")]
        public CustomerReference CustomerReference { get; set; }
        
        /// <summary>
        /// <para>Report parameters including report name, version, and filters (e.g., date ranges).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReportDefinition", Namespace="http://www.niso.org/schemas/sushi")]
        public ReportDefinition ReportDefinition { get; set; }
        
        /// <summary>
        /// <para>Date/time the request was created.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Created", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Created { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Created property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedSpecified { get; set; }
        
        /// <summary>
        /// <para>Identifier may be provided by client application for internal use/diagnostics.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="string")]
        public string ID { get; set; }
    }


    // Generated by the tool but results in the following error: 
    // Circular base class dependency involving 'Schemas.Sushi.ReportRequest' and 'Schemas.Sushi.ReportRequest'
    //[System.SerializableAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlRootAttribute("ReportRequest", Namespace="http://www.niso.org/schemas/sushi")]
    //public partial class ReportRequest : Schemas.Sushi.ReportRequest
    //{
    //}
    
    /// <summary>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("Activity", Namespace="http://www.niso.org/schemas/sushi")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Activity
    {
    }
}
