//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 0.5.5559.28274.
namespace Schemas.Sushi.Counter
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>This is the actual response expected from a COUNTER_SUSHI service. A combination of the SUSHI ReportResponse with the COUNTER "Report" added. NOTE: The ReportRequest and ReportResponse are defined in the SUSHI1_7.xsd and the COUNTER report is defined in the Counter4_1.xsd.</para>
    /// <para>The report response for COUNTER reports (CounterReportResponse).</para>
    /// </summary>
    [System.SerializableAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "0.5.5559.28274")]
    [System.Xml.Serialization.XmlTypeAttribute("CounterReportResponse", Namespace="http://www.niso.org/schemas/sushi/counter")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ReportResponse", Namespace="http://www.niso.org/schemas/sushi/counter")]
    public partial class CounterReportResponse : Schemas.Sushi.ReportResponse
    {
        
        /// <summary>
        /// <para>This represents the payload of the ReportResponsen by referencing the "Reports" element in the COUNTER schema.</para>
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute("Report", Namespace="http://www.niso.org/schemas/sushi/counter", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Report", Namespace="http://www.niso.org/schemas/counter")]
        public System.Collections.ObjectModel.Collection<Schemas.Counter.Report> Report { get; private set; }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="CounterReportResponse" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CounterReportResponse" /> class.</para>
        /// </summary>
        public CounterReportResponse()
        {
            this.Report = new System.Collections.ObjectModel.Collection<Schemas.Counter.Report>();
        }
    }
}
